### ISSUE TITLE
Releasing v6.0.0

### ISSUE THREAD

**Issue by aminya** [zeromq/zeromq.js#529]
I'd like to explain the project's status and track the remaining issues for v6.0.0.

The latest beta builds without any issues, and prebuilt binaries for many platforms are provided. 

The normal unit tests pass locally (`pnpm run test.skip_gc_tests`)

Some of the GC tests for some protocols fail (`pnpm run test`). However, I don't think these GC tests are crucial for functionality since the tests try to rely on GC's unpredictable behaviour. 

If there is an issue that actually blocks us from releasing v6.0.0 please leave a comment.

**Comment by ni-mkrieg** [comment]
this is a blocker for us on MacOS:
https://github.com/zeromq/zeromq.js/issues/530

**Comment by aminya** [comment]
@ni-mkrieg the issue is resolved now. Will appear in the new release soon.

**Comment by ni-mkrieg** [comment]
thanks, @aminya, will this be tagged as beta.11?

**Comment by aminya** [comment]
@ni-mkrieg This is fixed as of https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0-beta.11

**Comment by ni-mkrieg** [comment]
thanks, yes would be great if you could prevent the whole rebuild, it is not running for a good while and then I get this error on x64 Mac.

```
ld: library not found for -lsodium
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/zeromq.node] Error 1
rm 7722eaf02fcc073df28ffd1fa831e71544edfd42.intermediate
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/markus.krieg/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Users/markus.krieg/.nvm/versions/node/v16.13.0/bin/node" "/Users/markus.krieg/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/markus.krieg/git/native-access/node_modules/zeromq
```

**Comment by ni-mkrieg** [comment]
on arm64 / M1 I get this error right away:

```
-- Configuring incomplete, errors occurred!
See also "/Users/markus.krieg/git/native-access/node_modules/zeromq/build/libzmq-staging/build/CMakeFiles/CMakeOutput.log".
cmake --build ./build --config Release --target install
make[1]: Makefile: No such file or directory
make[1]: *** No rule to make target `Makefile'.  Stop.
  TOUCH Release/obj.target/libzmq.stamp
  CXX(target) Release/obj.target/zeromq/src/context.o
In file included from ../src/context.cc:2:
In file included from ../src/context.h:4:
../src/prefix.h:7:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
         ^~~~~~~
1 error generated.
make: *** [Release/obj.target/zeromq/src/context.o] Error 1
rm 7722eaf02fcc073df28ffd1fa831e71544edfd42.intermediate
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/Cellar/node@14/14.20.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/opt/homebrew/Cellar/node@14/14.20.0/bin/node" "/opt/homebrew/Cellar/node@14/14.20.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/markus.krieg/git/native-access/node_modules/zeromq
```

**Comment by aminya** [comment]
This issue can be fixed by installing sodium
```
brew install libsodium gnutls
```

Could you install zeromq with `npm i --verbose`. node-gyp-build doesn't give the reason why the prebuild is not picked up.
 https://github.com/prebuild/node-gyp-build/issues/54

**Comment by ni-mkrieg** [comment]
Good news, with sodium installed it did not rebuild on x64 at all any more, testing on arm64 now. I hope sodium is preinstalled on Github servers!

**Comment by aminya** [comment]
I am working on the node-gyp-build's preinstall logic:
https://github.com/prebuild/node-gyp-build/pull/55

Hopefully, that is merged soon, and you will not need to do a rebuild!

**Comment by ni-mkrieg** [comment]
That would be very cool, even after installing sodium on M1 it is currently still rebuilding indeed. So sodium installed prevented rebuild on x64 but not arm64. Actually I am not 100% sure the brew install for libsodium worked on arm, still getting this line:

```
ld: library not found for -lsodium
```

The `yarn install --verbose` did not contain much useful information either.

```
verbose 53.652263084 Error: /Users/markus/git/native-access/node_modules/zeromq: Command failed.
Exit code: 1
Command: (shx test -f ./script/build.js || run-s build.js) && node-gyp-build
Arguments: 
Directory: /Users/markus/git/native-access/node_modules/zeromq
Output:
dyld[91022]: missing symbol called

Downloading libzmq source from https://github.com/zeromq/libzmq/releases/download/v4.3.4/zeromq-4.3.4.tar.gz
Building libzmq Release
```

**Comment by ni-mkrieg** [comment]
Okay so an x64 this is the reason why it rebuilds, I believe because it cannot find libsodium that is needed by your precompiled binary? THat would also explain why it does not recompile after I install libsodium via homebrew. is there a way for you to compile that lib into your prebuild binary and not dynamically link to it?

```
verbose 108.080591296 Error: /Users/markus/git/native-access/node_modules/zeromq: Command failed.
Exit code: 1
Command: (shx test -f ./script/build.js || run-s build.js) && node-gyp-build
Arguments: 
Directory: /Users/markus/git/native-access/node_modules/zeromq
Output:
node:internal/modules/cjs/loader:1183
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/markus/git/native-access/node_modules/zeromq/prebuilds/darwin-x64/node.napi.glibc.node, 1): Library not loaded: /usr/local/opt/libsodium/lib/libsodium.23.dylib
  Referenced from: /Users/markus/git/native-access/node_modules/zeromq/prebuilds/darwin-x64/node.napi.glibc.node
  Reason: image not found
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at load (/Users/markus/git/native-access/node_modules/node-gyp-build/index.js:22:10)
    at Object.<anonymous> (/Users/markus/git/native-access/node_modules/node-gyp-build/build-test.js:19:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by ni-mkrieg** [comment]
all good if we do not have to rebuild, was more worried about your own CI.yml file having to do this for each build:

```
- name: Install Mac-OS Dependencies
        if: contains(matrix.os, 'macos')
        run: |
          brew install libsodium gnutls
```

were you able to avoid the rebuild on Mac x64 and arm64 - ideally without us having to install libsodium? it worked fine without libsodium installed in beta.6 for Mac x64...

**Comment by aminya** [comment]
That snippet is just to declare the dependencies to be more accurate. In practice it does nothing because it is already installed:
https://github.com/zeromq/zeromq.js/actions/runs/3483046346/jobs/5826083947#step:7:11

You will need the libsodium dynamic library in either case during runtime. Without that library, the connections will not be secure.

Regarding the rebuild, I am still handling the external `node-gyp-build` issues. Please stay tuned.

**Comment by bfan1256** [comment]
I have done brew install and ran a verbose and can see that libsodium is found But it just happens at the final linking step that it just can't find `-lsodium`

**Comment by td-krzysiek** [comment]
Hello,

Exactly the same issue here on M1, full log:

[2022-11-22T11_35_47_985Z-debug-0.log](https://github.com/zeromq/zeromq.js/files/10067016/2022-11-22T11_35_47_985Z-debug-0.log)

**Comment by td-krzysiek** [comment]
Hi,

I actually added one like to fix this

```
link_directories(${SODIUM_LIBRARY_DIRS})
```

below this line:
https://github.com/zeromq/libzmq/blob/master/CMakeLists.txt#L269
node_modules/zeromq/build/libzmq/zeromq-4.3.2/CMakeLists.txt

and then to rebuild:

```
cd node_modules/zeromq
../.bin/node-gyp-build
```

**Comment by aminya** [comment]
@td-krzysiek could you make a pull request in that repository?

**Comment by td-krzysiek** [comment]
Done & looking forward for the V6 release 👍

**Comment by DonJayamanne** [comment]
Hi, Thank you for looking into releasing a new version.
I'm one of the engineers working on the Jupyter extension for VS  Code
This package is used to communicate with Jupyter kernels (python kernels) over zmq

We found that the package fails in some cases which you may be aware of
You have requested this new version to be tested here https://github.com/microsoft/vscode-jupyter/issues/10386#issuecomment-1315042452

I'll test this and get back to you with a confirmation.
Again thanks for your contribution to this project

**Comment by aminya** [comment]
> Done & looking forward for the V6 release 👍

The fix is merged! Now on master.

**Comment by bfan1256** [comment]
Awesome! We want to start testing this integration. Could you push up an NPM release?

**Comment by aminya** [comment]
v6.0.0-beta.12 is released with the latest changes!

**Comment by bfan1256** [comment]
Looks like I'm still getting the same issue with the -LSodium

**Comment by td-krzysiek** [comment]
Yep, I confirm this, the problem is that zeromq.js is compiling `node_modules/zeromq/build/libzmq/zeromq-4.3.2` which isn't master but exact 4.3.2 release and link_libraries line is missing there.

**Comment by aminya** [comment]
Ok, try v6.0.0-beta.13. I forked node-gyp-build, and published my fixes. This should skip rebuilding, and if it does, it will give a clear message.

**Comment by bfan1256** [comment]
```[4/4] 🔨  Building fresh packages...
[8/8] ⠠ zeromq
[-/8] ⠠ waiting...
[7/8] ⠠ core-js-pure
[-/8] ⠠ waiting...
error /Users/-------/code/node_modules/zeromq: Command failed.
Exit code: 127
Command: (shx test -f ./script/build.js || run-s build.js) && node-gyp-build
Arguments: 





```

**Comment by td-krzysiek** [comment]
https://github.com/zeromq/zeromq.js/blob/master/binding.gyp#L86

I replaced it with ```'<!@(pkg-config libsodium --libs)',```, and it seems to work now.

**Comment by aminya** [comment]
Please test `v6.0.0-beta.14`. It should give more information on the reason for the rebuild.

**Comment by Y-qwq** [comment]
> Please test `v6.0.0-beta.14`. It should give more information on the reason for the rebuild.

I have the following errors when installing beta.14 in MacOS(12.6 M1)

MacBook Air (M1, 2020)


```
install$ (shx test -f ./script/build.js || run-s build.js) && cross-env npm_config_build_from_source=true node-gyp-build
│ dyld[72929]: missing symbol called
└─ Failed in 233ms
```

**Comment by aminya** [comment]
Maybe we should include the `libsodium.dyld` in the package too so you don't have to install it manually.

**Comment by kavsingh** [comment]
am seeing similar to https://github.com/zeromq/zeromq.js/issues/529#issuecomment-1328701248 when installing on an m1 MacBook pro 2020, macos 13.0.1

via yarn
```bash
❯ yarn                
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
error /<path to project>/node_modules/zeromq: Command failed.
Exit code: 1
Command: (shx test -f ./script/build.js || run-s build.js) && cross-env npm_config_build_from_source=true node-gyp-build
Arguments: 
Directory: /<path to project>/node_modules/zeromq
Output:
dyld[44504]: missing symbol called
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

via npm
```bash
❯ rm -rf node_modules/ && npm i 
npm ERR! code 1
npm ERR! path /<path to project>/node_modules/zeromq
npm ERR! command failed
npm ERR! command sh -c (shx test -f ./script/build.js || run-s build.js) && cross-env npm_config_build_from_source=true node-gyp-build
npm ERR! dyld[44714]: missing symbol called

npm ERR! A complete log of this run can be found in:
npm ERR!     /<user dir>/.npm/_logs/2022-11-28T19_33_05_054Z-debug-0.log
```
libsodium is also installed on the machine via brew

```
❯ brew info libsodium   
==> libsodium: stable 1.0.18 (bottled), HEAD
NaCl networking and cryptography library
https://libsodium.org/
/opt/homebrew/Cellar/libsodium/1.0.18_1 (73 files, 778.0KB) *
  Poured from bottle on 2022-11-28 at 20:32:01
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libsodium.rb
License: ISC
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 106,038 (30 days), 328,370 (90 days), 1,317,655 (365 days)
install-on-request: 1,394 (30 days), 4,407 (90 days), 21,084 (365 days)
build-error: 2 (30 days)

❯ node --version
v16.15.0
```


> You will need the libsodium dynamic library in either case during runtime

To clarify, would this mean if deploying an app that depends on zeromq.js to end users, we need to ensure the libsodium dynamic library is present on the end user machine as well? if so

> Maybe we should include the libsodium.dyld in the package too

would be great 🙏

**Comment by aminya** [comment]
It seems that these errors only happen on Arm macOS. Can someone confirm that by testing it on macOS x86?

**Comment by kavsingh** [comment]
@aminya errors do not occur and installation is successful on x86 MacBook pro 2020, macOS 13.0. looks like M1 only

```bash
❯ yarn
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
:sparkles:  Done in 14.95s.
```

```bash
❯ brew info libsodium
==> libsodium: stable 1.0.18 (bottled), HEAD
NaCl networking and cryptography library
https://libsodium.org/
/usr/local/Cellar/libsodium/1.0.18_1 (73 files, 1MB) *
  Poured from bottle on 2020-11-24 at 21:29:14
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libsodium.rb
License: ISC
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 109,598 (30 days), 327,918 (90 days), 1,319,730 (365 days)
install-on-request: 1,467 (30 days), 4,409 (90 days), 21,065 (365 days)
build-error: 2 (30 days)
```

**Comment by aminya** [comment]
> looks like failures on Arm M1 macs only

Ok, so cross-compiling for Arm M1 from x86 doesn't seem to work properly here. Contributions are welcome!

**Comment by td-krzysiek** [comment]
@aminya what contribution you have in mind? Can look into this if we have something well defined.

**Comment by aminya** [comment]
Since no CI service provides MacOS Arm machines, the only way to build that is by cross-compiling. 
Please clone the repo on a x86 Mac and run 

```
ARCH=arm64 pnpm install
ARCH=arm64 pnpm run prebuild
```

This should cross-compile for Arm. See if the build gives any errors or warnings, and then try to test the generated binary on an Arm machine to see if it works.

**Comment by td-krzysiek** [comment]
Okay, I have access to mac x86 computers at work, will be able to try this tomorrow.

**Comment by Bartel-C8** [comment]
> Since no CI service provides MacOS Arm machines, the only way to build that is by cross-compiling. Please clone the repo on a x86 Mac and run
> 
> ```
> ARCH=arm64 pnpm install
> ARCH=arm64 pnpm run prebuild
> ```
> 
> This should cross-compile for Arm. See if the build gives any errors or warnings, and then try to test the generated binary on an Arm machine to see if it works.

Just reporting for my case on my Macbook Pro (Intel)

Called: `ARCH=arm64 pnpm install`

```
Package libsodium was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsodium.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsodium' found
gyp: Call to 'pkg-config libsodium --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

libsodium is installed though via `homebrew`. After 
`export PKG_CONFIG_PATH=/usr/local/Cellar/libsodium/1.0.18_1/lib/pkgconfig/` the install runs fine with following warning(!) (which I see on the github actions builds as well):

```
ld: warning: ignoring file /usr/local/Cellar/libsodium/1.0.18_1/lib/libsodium.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Users/bartel/git/zeromq.js/build/libzmq/lib/libzmq.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```

So I think, in any case, this won't work on arm as libsodium and libzmq are x86_64 buids...

Same warning after running `ARCH=arm64 pnpm run prebuild` :

ld: warning: ignoring file /usr/local/Cellar/libsodium/1.0.18_1/lib/libsodium.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64

**Comment by Bartel-C8** [comment]
Update, via this (https://github.com/Homebrew/discussions/discussions/2843#discussioncomment-2026915) way, I could install the arm version of libsodium (I am on macOS Ventura)
```
brew fetch --force --bottle-tag=arm64_ventura libsodium
brew reinstall /Users/bartel/Library/Caches/Homebrew/downloads/3c17065fa853b7c22748466684ac78dbc5cb7c7419db975572feaa3875521288--libsodium--1.0.18_1.arm64_ventura.bottle.tar.gz
```
(reinstall because libsodium was already installed)

`ARCH=arm64 pnpm install` still gives the warnings:
```
ld: warning: dylib (/usr/local/Cellar/libsodium/1.0.18_1/lib/libsodium.dylib) was built for newer macOS version (13.0) than being linked (11.0)
ld: warning: ignoring file /usr/local/Cellar/libsodium/1.0.18_1/lib/libsodium.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/bartel/git/zeromq.js/build/libzmq/lib/libzmq.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```

But `ARCH=arm64 pnpm run prebuild` is successful:
```
  SOLINK_MODULE(target) Release/zeromq.node
ld: warning: dylib (/usr/local/Cellar/libsodium/1.0.18_1/lib/libsodium.dylib) was built for newer macOS version (13.0) than being linked (11.0)
rm 7722eaf02fcc073df28ffd1fa831e71544edfd42.intermediate
gyp info ok 

```

So seems in the `install` step the passing of ARCH is somewhere missing?
I see this logging in the `install` case: (notice the arch=x64)

```
> zeromq@6.0.0-beta.14 install /Users/bartel/git/zeromq.js
> (shx test -f ./script/build.js || run-s build.js) && cross-env npm_config_build_from_source=true node-gyp-build

No native build was found for platform=darwin arch=x64 runtime=node abi=93 uv=1 libc=glibc node=16.3.0
    loaded from: /Users/bartel/git/zeromq.js
  ```

**Comment by aminya** [comment]
I have written a script that installs the Arm version of Brew on MacOS x86. Could you test to see if it works? It's a bit slow to make changes and wait for CI.
https://github.com/zeromq/zeromq.js/pull/542/files

**Comment by aminya** [comment]
v6.0.0-beta.15 was released:
* fix: statically link libsodium by @aminya in https://github.com/zeromq/zeromq.js/pull/540
* fix: install arm brew on macOS Arm to install libsodium by @aminya in https://github.com/zeromq/zeromq.js/pull/542
* fix: fixes for macOS-arm-deps script @Bartel-C8 in https://github.com/zeromq/zeromq.js/pull/543

**Comment by bfan1256** [comment]
I can confirm it is working with electron and next.js as well on arm :D.

Great work @aminya

**Comment by Bartel-C8** [comment]
On rebuilding for Electron with an Intel Mac, I also need the (path) to libsodium, should me mention it somewhere in the documentation/README?

Solution:

`brew install libsodium`

And

`export PKG_CONFIG_PATH=/usr/local/var/homebrew/linked/libsodium/lib/pkgconfig/`

Actually, it makes me wonder if I can change the compile-time checks into runtime checks, so no special build is needed for Electron... Would make things a lot easier!

**Comment by Bartel-C8** [comment]
> Actually, it makes me wonder if I can change the compile-time checks into runtime checks, so no special build is needed for Electron... Would make things a lot easier!

https://github.com/zeromq/zeromq.js/pull/546

**Comment by DonJayamanne** [comment]
Thanks, this now installs on a Mac M1, however when i test this when using in a product (Jupyter extension for VS Code used to communicate with with Python kernels over zmq) some things just don't work at all with this new build.
I know thats completely useless inforomation as I'm not telling you want fails and where, but i haven't dug into  this just yet. However i can confirm that the older version `^6.0.0-beta.6` works and the latest does not.

Will get you more information on what fails.
Once again thanks for your effor.

**Comment by Bartel-C8** [comment]
If @aminya could push a new release, it would be great if you could test that one @DonJayamanne .

The current latest beta release needs a manual rebuild for Electron-bases applications, which VS Code is... So hopefully with my latest changes, everything runs fine again...

**Comment by aminya** [comment]
v6.0.0-beta.16 was released with fixes for Electron and the documentation.

* fix: detect Electron version at runtime by @Bartel-C8 in https://github.com/zeromq/zeromq.js/pull/546
* test: Run mocha tests with Electron by @Bartel-C8 in https://github.com/zeromq/zeromq.js/pull/547
* docs: fix and automate the documentation generation by @aminya in https://github.com/zeromq/zeromq.js/pull/545
* docs: fix the docs issues by @aminya in https://github.com/zeromq/zeromq.js/pull/549
* chore: remove unused scripts by @aminya in https://github.com/zeromq/zeromq.js/pull/544

**Comment by DonJayamanne** [comment]
Tried it, while this new version does not crash the runtime host as it used to in the past, it doesn't work.
Once again, I haven't been able to pin point what fails and when, I will get this information some time tomorrow.

**Comment by Bartel-C8** [comment]
> export PKG_CONFIG_PATH=/usr/local/var/homebrew/linked/libsodium/lib/pkgconfig/

Actually this is a real pain, as exports are not being respected in the `sudo` environment, in which my Gitlab CI runner is running...
```
Bartels-MacBook-Pro:zeromq.js bartel$ sudo pkg-config libsodium --libs
Package libsodium was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsodium.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsodium' found
```

Running without `sudo` works because of the `PKG_CONFIG_PATH` being set...

**Comment by aminya** [comment]
> Tried it, while this new version does not crash the runtime host as it used to in the past, it doesn't work. Once again, I haven't been able to pin point what fails and when, I will get this information some time tomorrow.

Please open a new issue with the reproduction and error logs.

**Comment by Bartel-C8** [comment]
@aminya Best wishes for 2023!

I noticed a "problem" recently with shipping my application for linux.
The current CI build uses a very recent Ubuntu (22) version, which causes that the prebuilds are not very compatible with older systems/OS versions. (GLIBC + GLIBCXX versions)

In my case, I had to downstep my whole build environment (for an Electron) app to Debian 9, in order to rebuild zeromq/libzeromq.

What is your thought on maximizing the prebuilt versions' compatibility, thus downgrading the build OS-ses?

**Comment by crimx** [comment]
Also facing missing libsodium issue on a x64 Mac when `pnpm add zeromq@6.0.0-beta.15` (See logs below).

`brew install libsodium` fixes the issue. Does it mean if I distribute my package that depends on `zeromq`, other users have to install libsodium manually too?

```bash
pnpm add zeromq@6.0.0-beta.15  ✔  system   2.7.6   14:40:33

Packages: +32
++++++++++++++++++++++++++++++++
node_modules/.pnpm/zeromq@6.0.0-beta.15/node_modules/zeromq: Running install scrnode_modules/.pnpm/zeromq@6.0.0-beta.15/node_modules/zeromq: Running install script, failed in 22.4s2, reused 32, downloaded 0, added 0, done
.../node_modules/zeromq install$ (shx test -f ./script/build.js || run-s build
│ dlopen(/Users/xxx/code/test/node_modules/.pnpm/zeromq@6.0.0-beta.15/node_m
│   Referenced from: <8B4668BF-FD06-3E29-B4CA-BD2E6848AF6F> /Users/xxx/code/
│   Reason: tried: '/usr/local/opt/libsodium/lib/libsodium.23.dylib' (no such
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.3.1
│ gyp info using node@18.4.0 | darwin | x64
│ gyp info find Python using Python version 3.9.6 found at "/Applications/Xcod
│ gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/Users/xxx/Library/pnpm/global/5/.pnpm/pnpm@7.22.0/
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/xxx/code/eeex/node_modules/.pnpm/zeromq@6.0.
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/xxx/Library/pnpm/global/5/.pnpm/pnpm@7.22.0/
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/xxx/Library/Caches/node-gyp/18.4.0/include/n
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/Users/xxx/Library/Caches/node-gyp/
│ gyp info spawn args   '-Dnode_gyp_dir=/Users/xxx/Library/pnpm/global/5/.pn
│ gyp info spawn args   '-Dnode_lib_file=/Users/xxx/Library/Caches/node-gyp/
│ gyp info spawn args   '-Dmodule_root_dir=/Users/xxx/code/eeex/node_modules
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ Package libsodium was not found in the pkg-config search path.
│ Perhaps you should add the directory containing `libsodium.pc'
│ to the PKG_CONFIG_PATH environment variable
│ No package 'libsodium' found
│ gyp: Call to 'pkg-config libsodium --libs' returned exit status 1 while in b
│ gyp ERR! configure error
│ gyp ERR! stack Error: `gyp` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onCpExit (/Users/xxx/Library/pnpm/globa
│ gyp ERR! stack     at ChildProcess.emit (node:events:537:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_proce
│ gyp ERR! System Darwin 22.1.0
│ gyp ERR! command "/usr/local/Cellar/node/18.4.0/bin/node" "/Users/xxx/Libr
│ gyp ERR! cwd /Users/xxx/code/test/node_modules/.pnpm/zeromq@6.0.0-beta.15/
│ gyp ERR! node -v v18.4.0
│ gyp ERR! node-gyp -v v9.3.1
│ gyp ERR! not ok
└─ Failed in 22.4s at /Users/xxx/code/test/node_modules/.pnpm/zeromq@6.0.0-beta.15/node_modules/zeromq
Progress: resolved 32, reused 32, downloaded 0, added 0, done
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by aminya** [comment]
You must use the latest version that is currently `pnpm add zeromq@6.0.0-beta.16`

**Comment by crimx** [comment]
Sorry I copied from the [docs](http://zeromq.github.io/zeromq.js/).

Same issue with bata.16 without libsodium.

```bash
pnpm add zeromq@6.0.0-beta.16                                                                                                                                                                                                                                    1 ✘  25s  system   2.7.6   16:04:24
Packages: +32
++++++++++++++++++++++++++++++++
node_modules/.pnpm/zeromq@6.0.0-beta.16/node_modules/zeromq: Running install script, failed in 1.6s
.../node_modules/zeromq install$ (shx test -f ./script/build.js || run-s build.js) && cross-env npm_config_build_from_source=true node-gyp-build
│ dlopen(/Users/xxx/code/test/node_modules/.pnpm/zeromq@6.0.0-beta.16/node_modules/zeromq/prebuilds/darwin-x64/node.napi.glibc.node, 0x0001): Library not loaded: /usr/local/opt/libsodium/lib/libsodium.23.dylib
│   Referenced from: <00BDB276-A607-3D78-B10D-0899069B057C> /Users/xxx/code/test/node_modules/.pnpm/zeromq@6.0.0-beta.16/node_modules/zeromq/prebuilds/darwin-x64/node.napi.glibc.node
│   Reason: tried: '/usr/local/opt/libsodium/lib/libsodium.23.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libsodium/lib/libsodium.23.dylib' (no such file), '/usr/local/opt/libsodium/lib/libsodium.23.dylib' (no such file), '/usr/local/lib/libsodium.23.dylib' (no such file), '/usr/lib
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.3.1
│ gyp info using node@18.4.0 | darwin | x64
│ gyp info find Python using Python version 3.9.6 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
│ gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/Users/xxx/Library/pnpm/global/5/.pnpm/pnpm@7.22.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/xxx/code/test/node_modules/.pnpm/zeromq@6.0.0-beta.16/node_modules/zeromq/build/config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/xxx/Library/pnpm/global/5/.pnpm/pnpm@7.22.0/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/xxx/Library/Caches/node-gyp/18.4.0/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/Users/xxx/Library/Caches/node-gyp/18.4.0',
│ gyp info spawn args   '-Dnode_gyp_dir=/Users/xxx/Library/pnpm/global/5/.pnpm/pnpm@7.22.0/node_modules/pnpm/dist/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/Users/xxx/Library/Caches/node-gyp/18.4.0/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/Users/xxx/code/test/node_modules/.pnpm/zeromq@6.0.0-beta.16/node_modules/zeromq',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ Package libsodium was not found in the pkg-config search path.
│ Perhaps you should add the directory containing `libsodium.pc'
│ to the PKG_CONFIG_PATH environment variable
│ No package 'libsodium' found
│ gyp: Call to 'pkg-config libsodium --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
│ gyp ERR! configure error
│ gyp ERR! stack Error: `gyp` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onCpExit (/Users/xxx/Library/pnpm/global/5/.pnpm/pnpm@7.22.0/node_modules/pnpm/dist/node_modules/node-gyp/lib/configure.js:325:16)
│ gyp ERR! stack     at ChildProcess.emit (node:events:537:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
│ gyp ERR! System Darwin 22.1.0
│ gyp ERR! command "/usr/local/Cellar/node/18.4.0/bin/node" "/Users/xxx/Library/pnpm/global/5/.pnpm/pnpm@7.22.0/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
│ gyp ERR! cwd /Users/xxx/code/test/node_modules/.pnpm/zeromq@6.0.0-beta.16/node_modules/zeromq
│ gyp ERR! node -v v18.4.0
│ gyp ERR! node-gyp -v v9.3.1
│ gyp ERR! not ok
└─ Failed in 1.6s at /Users/xxx/code/test/node_modules/.pnpm/zeromq@6.0.0-beta.16/node_modules/zeromq
Progress: resolved 32, reused 32, downloaded 0, added 0, done
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Bartel-C8** [comment]
It's because `macos` also has the `"<!@(pkg-config libsodium --libs)",` dependency library in `binding.gyp`.

**Comment by aminya** [comment]
> dlopen(/Users/xxx/code/test/node_modules/.pnpm/zeromq@6.0.0-beta.16/node_modules/zeromq/prebuilds/darwin-x64/node.napi.glibc.node, 0x0001): Library not loaded: /usr/local/opt/libsodium/lib/libsodium.23.dylib

That is strange. The libsodium is built statically, but it still tries to link to the `dylib`.

**Comment by Bartel-C8** [comment]
> > dlopen(/Users/xxx/code/test/node_modules/.pnpm/zeromq@6.0.0-beta.16/node_modules/zeromq/prebuilds/darwin-x64/node.napi.glibc.node, 0x0001): Library not loaded: /usr/local/opt/libsodium/lib/libsodium.23.dylib
> 
> That is strange. The libsodium is built statically, but it still tries to link to the `dylib`. See `-DWITH_LIBSODIUM_STATIC=ON`
> 
> https://github.com/zeromq/zeromq.js/blob/47bb35c1941cb4fa8b510fb7da4d40b37cfa2e5f/script/build.ts#L81

That's strange indeed! I also notice now, with my bundled application: If I uninstall libsodium, I get the same error.
I think it _is_ because of the `"<!@(pkg-config libsodium --libs)",` which was also there for the macos config, which points to the dynamic library of libsodium.

Currently we are not building libsodium ourselves... We are linking to the static library.
Thus, on the machine that builds it (github CI or on a non-compatible pnpm install rebuild), `libdsodium` is currently required to be available `-DWITH_LIBSODIUM=ON -DWITH_LIBSODIUM_STATIC=ON`.


I think we have some options here:

We could add an option to build with/without CURVE. Are many people using it? Should the prebuilt binaries be shipped with/without then?

In either way, I think, when needing CURVE, libsodium is preferred, over tweetnacl, because of performance reasons. So we should avoid using tweetnacl as much as possible?

So we can:

- Either compile `libsodium` ourselves, always on build. Preferably with https://github.com/robinlinden/libsodium-cmake
- Need to find out why binding.gyp / node-gyp requires to know about libsodium...

**Comment by Bartel-C8** [comment]
I think it is because the CMake file of libzmq doesn't support linking `libsodium` statically properly:

https://github.com/zeromq/libzmq/blob/master/builds/cmake/Modules/FindSodium.cmake

It should point to the `.a` files, as e.g. supported in FindOpenSSL: https://github.com/Kitware/CMake/blob/master/Modules/FindOpenSSL.cmake#L184

https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_LIBRARY_SUFFIXES.html

**Comment by l1shen** [comment]
Same here on M1 Mac. `brew install libsodium` fixes the installation issue. But error `dyld[78762]: missing symbol called` throws when `require("zeromq")`.

**Comment by Bartel-C8** [comment]
> Same here on M1 Mac. `brew install libsodium` fixes the installation issue. But error `dyld[78762]: missing symbol called` throws when `require("zeromq")`.

Could you provide a full log of the installation and the error message? Normally, for macos, when libsodium is installed, it should work fine though. So that's interesting.

**Comment by l1shen** [comment]
```js
// index.js
const zmq = require("zeromq");
```

```shell
 node index.js
dyld[35815]: missing symbol called
[1]    35815 abort      node index.js
```

**Comment by l1shen** [comment]
```shell
❯ otool -L node_modules/zeromq/build/Release/zeromq.node
node_modules/zeromq/build/Release/zeromq.node (architecture x86_64):
	/usr/local/opt/libsodium/lib/libsodium.23.dylib (compatibility version 27.0.0, current version 27.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.36.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
node_modules/zeromq/build/Release/zeromq.node (architecture arm64):
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.36.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```

**Comment by robdivincenzo** [comment]
Not sure if this is the right place but I had the same libsodium issue & error as @crimx on an M1 macOS running `npm install zeromq`. Running `brew install libsodium` did not entirely fix it for me.

The error says it tried `/usr/local/lib/libsodium.23.dylib (no such file)` but that is the directory homebrew uses for Intel while homebrew's default directory for M1 is actually `/opt/homebrew/` according to: https://docs.brew.sh/Installation. And indeed that is where homebrew installs libsodium on my M1 macbook.

As a workaround, creating a symbolic link in homebrew's directory for Intel to the homebrew's directory for M1 allowed it to build successfully: `sudo ln -s /opt/homebrew/lib/libsodium.23.dylib /usr/local/lib/libsodium.23.dylib` but that isn't ideal.

**Comment by aminya** [comment]
Reported the issue upstream.
https://github.com/zeromq/libzmq/issues/4484

My temporary solution would be to include the dynamic libraries in the package by copying them beside the `.node` files in the prebuilds directory.  Contributions for doing this are welcome!

**Comment by smitalm** [comment]
@aminya is this still blocking 6.0.0 release? Linked upstream issue was closed https://github.com/zeromq/libzmq/issues/4484

**Comment by aminya** [comment]
Notified the core members to see what we can do about the upstream issue.

**Comment by DonJayamanne** [comment]
@aminya I just found out that there are no longer any arm builds for linux,
The only builds for linux is `linux-x64`, one of the previous version `^6.0.0-beta.6` had `linux-x64`, `linux-arm`, `linux-arm64`
Was this deliberate or just an oversight?

**Comment by denyeo** [comment]
I've not been able to get the prebuilt binaries on Node 18.15 on Ubuntu 20.04. I also tried the `node:18.15.0-slim` Docker image, but it doesn't get the binaries either.

It looks like [all the latest `node` images](https://hub.docker.com/_/node/tags) include Debian 11, which only has glibc 2.31, while 6.0.0 required glibc 2.33. I believe glibc shouldn't be upgraded either, since it's a system package.

Is there a publicly available, recent `node` image that works for prebuilt binaries? Alpine ones?

**Comment by Bartel-C8** [comment]
The glibc dependency on linux(/debian) is awful. 

I use zeromq.js in a production environment where I don't have any influence on the host OS. Which means I already experienced users which could not open the application because they had an older glibc. 
I now build on a Debian 9 ancient docker image to maximise glibc compatibility, which uses v2.24.

It would be awesome if the prebuilt did the same thing, so maximum compatibility is guaranteed by default. Now indeed it's being build by Ubuntu 22, which uses glibc 2.33.
(Which means e.g. that Ubuntu 18 and Ubuntu 20 are not supported, unless built yourself on an older machine).
Would this be possible in the current CI setup @aminya ?

**Comment by aminya** [comment]
Just to clarify, this issue is not unique to zeromq.js, and it only happens for Linux where the dependencies are shared libraries:
https://github.com/nodejs/node-gyp/issues/2297#issuecomment-755056371

What we can do is to compile on multiple Ubuntu versions so that it covers all the GlibC versions. Sometimes binaries compiled with older Glibc work on the newer versions.

**Comment by Bartel-C8** [comment]
@aminya : Won't the binary always work when compiled with an older glibc version? As newer glibc versions are always backwards compatible? 

So best would be to compile (just one?) prebuilt with the (reasonably) oldest glibc version? That way, like in my case, an end-provider should not care about it's build system and glibc version, as automatically the prebuilt with the old glibc compatibility is linked?

Maybe also good to mention in the readme docs that this could be an issue.

**Comment by aminya** [comment]
The issue is not GlibC. I think you have mistaken GLibCXX for GLIBC here.

**Comment by aminya** [comment]
Released `v6.0.0-beta.17`. Please update your versions, and try again.

**Comment by denyeo** [comment]
Thank you @aminya for the changed prebuild, and @Bartel-C8 for the detailed feedback!

**Comment by aminya** [comment]
I issues a statement regarding the status of zeromq.js here:

https://github.com/zeromq/zeromq.js/issues/576

**Comment by aminya** [comment]
v6.0.0 was released!  Here we go:
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
